[project]
name = "jsonl-utils"
version = "0.1.0"
description = "Utilities for working with JSONL files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "rich-click>=1.8.3",
]
[project.scripts]
jsonl = "jsonl_utils:main"
